# Texts used by the PDFView control - English (default)
# Encoding: UTF-8

pdf-view.tooltip.show-all=Show all / whole page
pdf-view.tooltip.show-thumbnails=Show thumbnails
pdf-view.tooltip.previous-page=Show previous page
pdf-view.tooltip.next-page=Show next page
pdf-view.tooltip.current-page=Current page number
pdf-view.tooltip.total-pages=Total number of pages
pdf-view.tooltip.rotate-left=Rotate page left
pdf-view.tooltip.rotate-right=Rotate page right
pdf-view.tooltip.clear-search=Clear search text
pdf-view.tooltip.previous-search-result=Go to previous search result
pdf-view.tooltip.next-search-result=Go to next search result
pdf-view.menu.copy=Copy
pdf-view.label.zoom=Zoom
pdf-view.search.prompt=Search ...
pdf-view.search.done=Done
pdf-view.search.summary=Found {0} occurrences on {1} pages
pdf-view.search.result.page=Page {0}
pdf-view.search.result.matches={0,choice,1#1 match|1<{0} matches}
pdf-view.error.not-searchable=Document is not searchable.
